version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: us-central1-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IGNITEDAPI}
    command: ["npm", "start"]

  workers:
    build:
      context: .
      dockerfile: Dockerfile
    image: us-central1-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IGNITEDAPI_WORKERS}
    command: ["node", "all-workers.js"]

  ignitedapi_scheduler:
    build:
      context: .
      args:
        CMD: node workers/scheduled/poc-warning.js
    image: ignitedapi-scheduler
