name: Build & Deploy to Cloud Run (Development)

on:
  push:
    branches:
      - gcp-devtest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud using WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.ARTIFACT_DOMAIN }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Print authenticated service account
        run: |
          echo "Authenticated account:"
          gcloud auth list
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          curl -s https://oauth2.googleapis.com/tokeninfo?access_token=$ACCESS_TOKEN | jq .

      - name: Build and Push container images (App + Worker)
        run: |
          docker build -t ${{ secrets.ARTIFACT_DOMAIN }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}/${{ secrets.APP_IMAGE }} . --build-arg CMD="npm start"
          docker build -t ${{ secrets.ARTIFACT_DOMAIN }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}/${{ secrets.WORKER_IMAGE }} . --build-arg CMD="node all-workers.js"

          docker push ${{ secrets.ARTIFACT_DOMAIN }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}/${{ secrets.APP_IMAGE }}
          docker push ${{ secrets.ARTIFACT_DOMAIN }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}/${{ secrets.WORKER_IMAGE }}

      - name: Check if Cloud Run service exists
        id: check-run
        run: |
          if gcloud run services describe ${{ secrets.CLOUD_RUN }} --region=${{ secrets.REGION }} --platform=managed; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy App to Cloud Run
        if: steps.check-run.outputs.exists == 'true'
        run: |
          gcloud run deploy ${{ secrets.APP_IMAGE }} \
            --image=${{ secrets.ARTIFACT_DOMAIN }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}/${{ secrets.APP_IMAGE }} \
            --region=${{ secrets.REGION }} \
            --platform=managed \
            --set-env-vars="NODE_ENV=development" \
            --allow-unauthenticated \
            --quiet

      - name: Deploy Worker to Cloud Run
        if: steps.check-run.outputs.exists == 'true'
        run: |
          gcloud run deploy ${{ secrets.WORKER_IMAGE }} \
            --image=${{ secrets.ARTIFACT_DOMAIN }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}/${{ secrets.WORKER_IMAGE }} \
            --region=${{ secrets.REGION }} \
            --platform=managed \
            --set-env-vars="NODE_ENV=development" \
            --allow-unauthenticated \
            --quiet
